- set_fact:
    myvars: "{{ swvars[inventory_hostname] }}"

- name: Set up interfaces
  nclu:
    atomic: true
    commands:
    - add interface {{ myvars.ints }} mtu 9216
    - add loopback lo ip address {{ myvars.loopback }}
